### ISSUE TITLE
is it possible choose a live stream

### ISSUE THREAD

**Issue by testermania** [abskmj/youtube-hls-m3u8#6]
some channels have multiple live stream. It would be nice if we could choose what we want.

**Comment by nasircsms** [comment]
this issue is still there.. any channel having multiple live streams result in failure..

`Error: Stream not found for Youtube URL: https://www.youtube.com/channel/UCMmpLL2ucRHAXbNHiCPyIyg/live<br> &nbsp; &nbsp;at getLiveStream (/home/vagrant/setup-apps/scrappers/youtube-iptv-channels/src/app.js:30:15)<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:95:5)<br> &nbsp; &nbsp;at async /home/vagrant/setup-apps/scrappers/youtube-iptv-channels/src/app.js:73:30`
